### ISSUE TITLE
AttributeError: module 'imgui' has no attribute 'begin_table'

### ISSUE THREAD

**Issue by Drothi** [mCodingLLC/VideosSampleCode#10] opened 2022-03-06 13:13 UTC
I tested the demo.py (renamed to imguitest.py) and it works, but if I try the tab bar the program crashes with the following Messages:

PS C:\Microsoft VS Code\Projekte> & "C:/Microsoft VS Code/Python/python.exe" "c:/Microsoft VS Code/Projekte/imguitest.py"
Traceback (most recent call last):
  File "c:/Microsoft VS Code/Projekte/imguitest.py", line 296, in <module>
    main()
  File "c:/Microsoft VS Code/Projekte/imguitest.py", line 289, in main
    render_frame(impl, window, jb)
  File "c:/Microsoft VS Code/Projekte/imguitest.py", line 245, in render_frame
    frame_commands()
  File "c:/Microsoft VS Code/Projekte/imguitest.py", line 180, in frame_commands
    if imgui.begin_tab_bar("MyTabBar"):
AttributeError: module 'imgui' has no attribute 'begin_tab_bar'

Can anyone help?

**Comment by mCodingLLC** [comment] 2022-03-06 17:29
This issue stems from the fact that when you `pip install` you get the latest published version, not the dev version, which is what my PR was based off of (remember from the video these are hundreds of commits apart). As such the things in the delta from the current release to the dev branch will crash. To try the dev branch or my PR you would have to `git clone` and checkout your desired commit, then `pip install -e . -v` (or replace . with the location where you cloned).

Tab bars are not essential to the demo so if you just want to try imgui you can comment that out.

Hope this helps!

Duplicate of: https://github.com/mCodingLLC/VideosSampleCode/issues/8

**Closed by mCodingLLC** 2022-03-06 17:29 UTC
